name: Flutter CI/CD

on:
  push:
    branches:
      - main   # hoặc nhánh bạn muốn theo dõi
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # macOS để build iOS và Android cùng lúc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java (cho Android)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      # Android build
      - name: Build Android APK
        run: flutter build apk --release

#      # iOS build
#      - name: Install CocoaPods dependencies
#        run: |
#          cd ios
#          pod install --repo-update
#          cd ..
#
#      - name: Build iOS IPA
#        run: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/ios/ipa/*.ipa
